complete -c tag -s l -l list -d 'List tags'
complete -c tag -l export -d 'Export tagged ordered tags'
complete -c tag -l restore -r -d 'Restore archive'
complete -c tag -s a -l add -r -d 'Add tags'
complete -c tag -l append -r -d 'Add tags at end'
complete -c tag -l prepend -r -d 'Add tags at beginning'
complete -c tag -s r -l remove -r -d 'Remove tags'
complete -c tag -s s -l set -r -d 'Replace tags'
complete -c tag -l copy -d 'Copy ordered tags'
complete -c tag -s m -l match -r -d 'Match tags'
complete -c tag -s u -l usage -r -d 'Count tag usage'
complete -c tag -s f -l find -r -d 'Spotlight find'
complete -c tag -l move -r -d 'Move tag'
complete -c tag -l at -r -d 'Insertion position'
complete -c tag -l before -r -d 'Place before tag'
complete -c tag -l after -r -d 'Place after tag'
complete -c tag -l sorted-tags -d 'Sort displayed/final tags'
complete -c tag -l sort-tags -d 'Alias for --sorted-tags'
complete -c tag -s V -l reverse -d 'Reverse display order'
complete -c tag -s C -l case-sensitive -d 'Case-sensitive matching'
complete -c tag -s c -l color -d 'Color tags'
complete -c tag -l tagged-only -d 'List/export only tagged items'
complete -c tag -s n -l filename -d 'Show filenames'
complete -c tag -s N -l no-filename -d 'Hide filenames'
complete -c tag -s t -l tags -d 'Show tags'
complete -c tag -s T -l no-tags -d 'Hide tags'
complete -c tag -s g -l one-per-line -d 'One tag per line'
complete -c tag -s G -l comma-separated -d 'Comma-separated tags'
complete -c tag -s p -l slash -d 'Append slash to directories'
complete -c tag -s 0 -l null -d 'NUL-terminate records'
complete -c tag -l absolute -d 'Absolute paths'
complete -c tag -l file-info -d 'Include file size and mtime'
complete -c tag -l jsonl -d 'JSON Lines output'
complete -c tag -l ndjson -d 'Alias for --jsonl'
complete -c tag -l stdin -d 'Read newline-delimited paths'
complete -c tag -l stdin0 -d 'Read NUL-delimited paths'
complete -c tag -s A -l all -d 'Include hidden files'
complete -c tag -s e -l enter -d 'Enter directories'
complete -c tag -s R -l recursive -d 'Recursive traversal'
complete -c tag -s d -l descend -d 'Alias for recursive traversal'
complete -c tag -l no-follow-symlinks -d 'Do not recurse through symlinked directories'
complete -c tag -l follow-symlinks -d 'Follow symlinks (default)'
complete -c tag -l dry-run -d 'Preview mutations'
complete -c tag -l root -r -d 'Relocate restore root'
complete -c tag -l backup -r -d 'Write undo archive'
complete -c tag -l no-backup -d 'Disable undo archive'
complete -c tag -l sync-backup -d 'Sync each undo record'
complete -c tag -s h -l help -d 'Show help'
complete -c tag -s v -l version -d 'Show version'
